all:
  hosts:
    lab5_server:
      ansible_host: ${SERVER_IP}
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
      ansible_python_interpreter: /usr/bin/python3
  vars:
    app_name: "java-app"
    app_port: 8080
    db_name: "appdb"
    db_user: "appuser"
    db_password: "securepassword123"
